language: python
python:
  - "2.7"
install:
 - pip install -r requirements-test.txt
script:
  - coverage run test_dir_edit.py
  - python setup.py -q install
after_success:
  - coverage report --fail-under=100
