language: python
python:
  - "2.7"
  - "3.5"
install:
 - pip install -r requirements-test.txt
script:
  - coverage run test_dir_edit.py
  - coverage report --fail-under=100
  - python setup.py -q install
