---
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements-test.txt
script:
  - coverage run test_dir_edit.py
  - coverage report --fail-under=100
  - pylint *.py
  - flake8
  - python setup.py -q install
