---
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements-test.txt
script:
  - coverage run test_dir_edit.py
  - coverage report --fail-under=100
  - pylint *.py
  - flake8
  - python setup.py -q install
# For Python 3.7, https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905:
dist: xenial
sudo: required
