name: Test
on:
  push:
  schedule:
    - cron: "0 0 1 * *" # monthly
jobs:
  runs-on: ubuntu-latest
  strategy:
    fail-fast: false
    matrix:
      python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
  steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Lint code with pylint
      run: pylint *.py
    - name: Check code with flake8
      run: flake8
    - name: Install package
      run: python setup.py -q install
    - name: Test code with coverage
      run: |
        coverage run test_dir_edit.py
        coverage report --fail-under=100
